excid3/tailwindcss-stimulus-components

src/modal.js
Similar fix as  
https://github.com/excid3/tailwindcss-stimulus-components/pull/5 to only call close() on ESC key if modal is toggled.
=> Only call close() when modal is toggled

src/modal.js
With this added functionality, the modal will now save and restore the scroll position when the body gets locked. This way the body doesn't jump to the top every time you open a modal.
Also there was the `keyup` event missing in the example HTML at the top. Without it, you can't close the modal with the `esc` key.
=> Update modal to save and restore scroll position

README.md, docs/index.html, src/modal.js
Added `e.target.blur();` to address #17 
Also modified a few tailwind classes for the modal example so that the modal can be scrolled when the content overflows the screen.
=> 9 7 19/bugfix

README.md
If someone is just copying and pasting from the README, this update will prevent them from spending time trying to figure out why toggle isn't working correctly.
=> add Toggle to import for basic usage docs

src/modal.js
Prevents being unable to close modal background when navigating away while modal is open.
=> Use disconnect lifecycle event to close modal.

src/tabs.js
This fixes a bug where the anchor logic would always set `this.index` no matter if an anchor was in the url or not (it would always default to the index being set to 0). This fixes that, so we only set the index if an anchor is given - if not, we rely on the value of `data-tabs-index` if set.
Also, we now dispatch a new CustomEvent named `tsp:tab-change` (tsp for tailwindcss-stimulus-components). This makes it so you can listen to said event in a `data-action` inside one of the tab panels, something like: `data-action="change-tab@window->scroll#updateScrollPosition"`
=> Fix anchor bug + add event when switching tabs

README.md, docs/index.html, src/dropdown.js, src/index.js, src/slideover.js
This PR adds a slideover component, which is basically just a dropdown with a backdrop/overlay.
So I extended the `Dropdown` and added callbacks so that you can now do this:
```html
<div role="main" class="h-screen flex overflow-hidden bg-gray-100"
data-controller="slideover"
data-sidebar-inactive-class="-translate-x-full,opacity-0"
data-sidebar-active-class="translate-x-0,opacity-100"
data-sidebar-entering-class=""
data-sidebar-enter-timeout="300,300"
data-sidebar-leaving-class=""
data-sidebar-leave-timeout="300,300"
data-sidebar-active-target="#sidebar-target">
```
Note that the Dropdown remains fully functional, as this video demonstrates:
I'll add a demo and documentation, just let me know if this is at all interesting to you.
=> Add slideover component

README.md
Updated README to remove deprecated syntax.
i.e. change `data-target="tabs.tab"` to `data-tabs-target="tab"`, etc.
=> Update README to use new Stimulus.js v2 data-target syntax

README.md, __tests__/fixtures/index.html, docs/index.html, src/alert.js
The alerts had a minor glitch: their fixed container partially obscures
the underlying page for pointer events, including click and hover.  Evident
on the demo page, where the "View on Github" link is unusable.
The fix here is nullifying pointer events for the container and enabling
them only for the visible parts of the alert.
=> Fix pointer events when alerts visible.

src/dropdown.js
This apparently is needed for the `remove` of class `hidden` to work when you want to display the dropdown menu on page load by setting `data-dropdown-open-value="true"`
=> Move class toggling inside setTimeout

README.md, docs/index.html, src/dropdown.js
Users can also focus on the dropdown button if `tabindex="0"` is included.
They can toggle the dropdown with Space or Enter if the attribute `data-dropdown-target="button"` is included on the button.
Demo video of the feature and DOM changes https://share.getcloudapp.com/wbu9jn1G
I have tested this manually against the docs/index.html app locally. I tried shipping the built `dist/` in the PR to make the demo work but it didn't. Not sure what's going on there. So this PR is just the change, but not `dist/`.
=> [a11y] Allow button to be focused and toggle dropdown with space/enter.

src/toggle.js
openValueChanged function fires before connect(), this will run an unnecessary loop.
Also, since this.toggleClass is undefined, this function will add an undefined class to an element.
You can see it on the jumpstartrails.com website as well.
=> Fix undefined toggleClass in the toggle_controller.js

README.md
Updating the README to outline how the dropdown can be closed upon clicking on an item in the dropdown menu.
Required for Turbo previews to displayed as expected as outlined in https://github.com/excid3/tailwindcss-stimulus-components/issues/63#issuecomment-787528308
Fixes: #63
=> Dropdown documentation.

src/modal.js
In the modal controller, if a custom `backgroundId` was set, but the
default background markup was used, the id would not be applied.
As a result of this fix, the setting of `this.backgroundId` had to be
moved above configuring `this.backgroundHtml`.
=> Modal: Use custom backgroundId for default background

README.md, docs/index.html, src/color_preview.js, src/index.js
Hi,
The implementation is working outside of your documentation page but I can't figure out how to make it work inside of your docs. It always throws a JS error of `Cannot read property 'prototype' of undefined`. Maybe it's due to how the JS is being compiled?
All I did was drop in the JS, I didn't change any of the UMD bits.
Another docs related issue is I've set CSS classes on the color picker based on using this NPM package `"@tailwindcss/forms": "0.3.2"`. This isn't available in your docs so the color picker looks totally busted. Any suggestions on how you want to handle that? It took a lot of tinkering for it to look correct in all major browsers (with that form plugin). If you can make it look good without that plugin please do it up!
Here's a screenshot of what it looks like …
=> Add color picker and preview

README.md, docs/index.html, src/color_preview.js
In the current docs the `#` that's prepended to the input is a few pixels too tall. This patch removes a bit of top margin from the input to even them out. Now it matches the screenshot in the original color preview PR #73.
=> Fix color preview input being vertically offset by a few pixels

src/alert.js
The alert originally relied on hard coded values to determine the delay before removing or showing the alert. This is replaced with [Stimulus values](https://stimulus.hotwired.dev/reference/values) instead. A default is still supplied.
Likewise the animation of the alert was done through style attributes hard coded in the controller. However Tailwind has classes for this purpose as well. Using [Stimulus' css class API](https://stimulus.hotwired.dev/reference/css-classes) these can be supplied from the DOM too. No default is supplied, as the alert is simply dismissed after its removal delay (if any) has run out.
In the example markup the alert is placed within a div with a horizontal padding. This caused the alert to not be completely out of view, when it was removed from the DOM. I solved …
=> Configurable Alert

README.md, src/modal.js
Hey, this adds the option to change the backdrop color and transparency to match the overall site design. By default it will use the existing value - rgba(0, 0, 0, 0.8).
=> Add value for backdrop color to modal

README.md, src/modal.js
Sometimes we don't want the modal to restore the scroll position when it's closes. This would be a nice to have feature when scrolling to the top would cause a weird behaviour. Such as my example here
https://user-images.githubusercontent.com/38360603/151157420-77340309-9ce7-4614-affd-7ca28307684e.mov
Allows to disable restoring the scroll position via a value attribute.
`data-modal-restore-scroll-value ||= true`
=> Allow modal to not restore scroll

README.md, src/alert.js
Addresses https://github.com/excid3/tailwindcss-stimulus-components/issues/131.
- Document values and classes for `Alert` component.
- Use Stimulus V3's default values instead of checking for presence of the value attribute.
closes https://github.com/excid3/tailwindcss-stimulus-components/issues/131.
=> Alert docs

src/toggle.js
`event.preventDefault()` makes checkboxes behave very weird
before when a checkbox was clicked the checkbox would toggle the `toggeable` but the checkbox would not be checked.
This fixes that issue
=> Fix toggle controller for checkboxes

src/modal.js
This addresses the ability to let the modal know that it will or will not restore the scroll value.
When scrollValue is set to false, we need not to add negative top position for the body, moreover, we need not to remove it when unlocking scroll since it's not applied in lockScroll method.
=> only add negative top position if restoreScrollValue is true

src/dropdown.js
addresses #121 
When running lighthouse accessibility scan currently there is an issue with the `[aria-*]` attributes:
> [aria-*] attributes do not match their roles
> Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes. [Learn more](https://web.dev/aria-allowed-attr/?utm_source=lighthouse&utm_medium=devtools).
This PR moves the aria-* attributes from the dropdown controller element to the `buttonTarget` if there is one defined.
As mentioned in #121 the developer can/should manually add the `aria-controls` & `aria-labelledby` logic, `menu` and `menuitem` roles.
=> Fixes accessibility aria attributes

README.md, src/popover.js
Same as with the alerts. Popovers that are triggered by toggle events should have the ability to self dismiss without having to toggle the element again.
=> Adding the ability for the popover to auto dismiss

src/dropdown.js
I was using `dropdown` on an `input` controller watching for `focus` events:
```html
<input type="text" name="search" id="search"
placeholder="Search..."
data-action="focus->dropdown#toggle blur->dropdown#toggle focus@window->dropdown#hide">
```
Without this fix, I was getting the following error when the `blur` event on the document triggered `hide`:
```
Error invoking action "focus@window->dropdown#hide"
TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
at extended.hide (dropdown_controller.js:134:22)
at Binding.invokeWithEvent (stimulus.js:281:25)
at Binding.handleEvent (stimulus.js:253:18)
at EventListener.handleEvent (stimulus.js:31:25)
```
=> Ignore hide events that aren't from nodes

docs/modal.md
As per an issue I had here : #196 and @excid3 recommandation, it would be nice to add the existence of `data-model-open-value` for modals on its doc.
=> Reference data-model-open-value on the modal docs

src/slideover.js
While working on Stimulus LSP I noticed that the `slideover` controller has a duplicate `menu` target. The `dropdown` controller already defines that target and the `slideover` controller is therefore automatically inheriting it.
=> Remove duplicate `menu` target in `slideover` controller

src/tabs.js
indexValueChanged runs after initialize and before connect not allowing this.indexValue to update, causing the first tab to always open.
see: https://stimulus.hotwired.dev/reference/values#change-callbacks
closes #204
=> Ensures the correct tab opens when visiting a page via a link with a tab anchor

docs/modal.md, index.html, package.json, src/modal.js, test/fixtures/index.html, test/fixtures/modal.html, test/modal_test.js
- Fixes the modal due to a target mismatch on the [example site](https://excid3.github.io/tailwindcss-stimulus-components/).
- Updates the modal example
- Adds modal tests
=> Fix Modal Dialog References

web-test-runner.config.mjs
This may help reduce the failures we're seeing in CI and local. I actually got pretty consistent result of passing tests locally by reducing the concurrency option to 1.
Similar issue found [here](https://github.com/open-wc/open-wc/issues/1749#issuecomment-654826490)
=> Update web-test-runner concurrency to 1

docs/popover.md
Small doc fix, the `dismissAfter` value is part of the `popover` controller.
https://github.com/excid3/tailwindcss-stimulus-components/blob/78b1bfc03704ea93419ca5cf7a6d6c4414e69e29/src/popover.js#L27
=> Update popover.md - Fix dismiss-after-value attr name

src/popover.js
Small comment fix. The `data-action` is defined twice with left over copied mouseenter/mouseleave actions.
=> Update popover.js - Small Comment Fix

src/dropdown.js, src/modal.js, src/slideover.js
This PR changes the way event listeners are registered on `connect()` for a better removal as per the recommendation in [this](https://www.betterstimulus.com/events) manual.
> When you call .bind() on a function, it creates a new function. Therefore, calling bind twice means the add and remove eventListeners are calling different references of the function and the event wont be removed. Make sure that when adding and removing event listeners you use the same bound function reference.
=> fix: applies change to event listener registration and cleanup

src/alert.js, src/transition.js, test/alert_test.js, test/dropdown_test.js, test/popover_test.js, test/toggle_test.js, test/transition_test.js
Fixes issue https://github.com/excid3/tailwindcss-stimulus-components/issues/247 by putting duct tape over it.
=> Catch the finished promise AbortError and ignores it
